name: Upload wheels to S3

description: "Upload wheels to S3"

inputs:
  package_name:
    description: "name of the package the wheels are for"
    required: true
  artifact_name:
    description: "name of the artifact containing the wheels"
    required: true
  enable:
    description: "whether to upload to S3"
    required: true
  aws_role:
    description: "AWS role for the S3 upload"
    default: "installer-upload"
  vault_url:
    description: "the vault URL"
    required: true
  vault_token:
    description: "the vault token"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./dist

    - name: Install deps
      shell: sh
      run: apk add aws-cli

    - name: Vault Login
      uses: Chia-Network/actions/vault/login@main
      with:
        vault_url: ${{ inputs.vault_url }}
        role_name: github

    - name: Get ephemeral aws credentials
      uses: Chia-Network/actions/vault/aws-sts@main
      with:
        vault_url: ${{ inputs.vault_url }}
        vault_token: ${{ inputs.vault_token }}
        role_name: ${{ inputs.aws_role }}

    - name: Upload Wheels
      if: inputs.enable == 'true'
      shell: sh
      working-directory: dist
      run: |
        echo just showing that we are running here, would be uploading to s3
        ls -la dist/${{ inputs.package_name }}-*.whl
        # TODO: enable once we think it is properly gated
        # ls dist/${{ inputs.package_name }}-*.whl | xargs -I % sh -c 'aws s3 cp % s3://download.chia.net/simple/${{ inputs.package_name }}/'
