name: Upload wheels to S3

description: "Upload wheels to S3"

inputs:
  package_name:
    description: "name of the package the wheels are for"
    required: true
  artifact_name:
    description: "name of the artifact containing the wheels"
    required: true
  dry_run:
    description: "whether to upload to S3"
    required: true
  aws_role:
    description: "AWS role for the S3 upload"
    default: "installer-upload"
  aws_account:
    description: "AWS account ID that the AWS role belongs to"
    required: true
  vault_url:
    description: "the vault URL"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: ${{ inputs.artifact_name }}-*
        path: ./dist
        merge-multiple: true

    - uses: actions/upload-artifact@v4
      with:
        name: wheel
        path: ./dist
        if-no-files-found: error

    - name: Install deps
      shell: sh
      run: |
        ( command -v apk && apk add aws-cli ) || true
        ( command -v apt-get && apt-get update && apt-get install -y awscli ) || true

    - name: Configure AWS credentials
      if: inputs.aws_account != ''
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/${{ inputs.aws_role }}
        aws-region: us-west-2

    - name: List existing wheels
      if: inputs.aws_account != ''
      shell: sh
      run: |
        # making sure the parent exists and the command works
        aws s3 ls s3://download.chia.net/simple/
        # continue assuming no existing wheels when the directory does not exist
        aws s3 ls s3://download.chia.net/simple/${{ inputs.package_name }}/ > existing_wheel_list_raw || true
        cat existing_wheel_list_raw
        cat existing_wheel_list_raw | tr -s ' ' | cut -d ' ' -f 4 > existing_wheel_list

    - name: List new wheels
      shell: sh
      run: |
        (cd dist/; ls ${{ inputs.package_name }}-*.whl) > new_wheel_list
        cat new_wheel_list | xargs -I % sh -c 'ls -l dist/%'

    - name: Choose wheels to upload
      if: inputs.aws_account != ''
      shell: sh
      continue-on-error: ${{ inputs.dry_run == 'true' }}
      run: |
        grep -F -x -v -f existing_wheel_list new_wheel_list > upload_wheel_list || true
        cat upload_wheel_list

    - name: Upload wheels
      if: inputs.aws_account != '' && inputs.dry_run == 'false'
      shell: sh
      run: |
        cat upload_wheel_list | xargs -I % sh -c 'aws s3 cp dist/% s3://download.chia.net/simple/${{ inputs.package_name }}/'
