name: "📦🚀 miniupnpc"

on:
  push:
    branches:
    - long_lived/**
    - main
    - release/**
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:
    inputs:
      version:
        description: "The version to build"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || format('{0}-{1}-{2}', github.ref, github.event_name, github.ref == 'refs/heads/main' && github.sha || '') }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  default_version: '2.3.3'
  name: miniupnpc
  pip_options: '--index-url https://pypi.chia.net/simple --extra-index-url https://pypi.org/simple'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: ${{ matrix.os.emoji }} 📦 Build ${{ matrix.arch.name }} ${{ matrix.python.major-dot-minor }}
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macOS
            file-name: macos
            matrix: macos
            emoji: 🍎
            runs-on:
              arm: [macos-13-arm64]
              intel: [macos-13]
            cibw-archs-macos:
              arm: arm64
              intel: x86_64
            macosx-deployment-target:
              arm: 13.0
              intel: 13
          - name: Linux
            file-name: linux
            matrix: linux
            emoji: 🐧
            runs-on:
              arm: [Linux, ARM64]
              intel: [ubuntu-latest]
          - name: Windows
            file-name: windows
            matrix: windows
            emoji: 🪟
            runs-on:
              intel: [windows-latest]
        python:
          - major-dot-minor: '3.9'
            cibw-build: 'cp39-*'
            manylinux: manylinux_2_28
            matrix: '3.9'
          - major-dot-minor: '3.10'
            cibw-build: 'cp310-*'
            manylinux: manylinux_2_28
            matrix: '3.10'
          - major-dot-minor: '3.11'
            cibw-build: 'cp311-*'
            manylinux: manylinux_2_28
            matrix: '3.11'
          - major-dot-minor: '3.12'
            cibw-build: 'cp312-*'
            manylinux: manylinux_2_28
            matrix: '3.12'
        arch:
          - name: ARM
            file-name: arm
            matrix: arm
          - name: Intel
            file-name: intel
            matrix: intel
        exclude:
          - os:
              matrix: windows
            arch:
              matrix: arm

    env:
      FILE_NAME: ${{ matrix.os.file-name }}-${{ matrix.arch.file-name }}-${{ matrix.python.major-dot-minor }}

    steps:
      - name: Clean workspace
        uses: Chia-Network/actions/clean-workspace@main

      - uses: Chia-Network/actions/setup-python@main
        with:
          python-version: ${{ matrix.python.major-dot-minor }}

      - uses: Chia-Network/actions/create-venv@main
        id: create-venv

      - uses: Chia-Network/actions/activate-venv@main
        with:
          directories: ${{ steps.create-venv.outputs.activate-venv-directories }}

      # - name: Get source dist
      #   run: |
      #     pip download ${{ env.pip_options }} --no-deps --no-binary :all: --dest packages ${{ env.name }}==${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || env.default_version }}

      # - name: Untar
      #   run: |
      #     tar -xvzf packages/${{ env.name }}-*
      #     mv ${{ env.name }}-* source

      - uses: actions/checkout@v4
        with:
          repository: miniupnp/miniupnp
          ref: miniupnpc_2_3_3
          path: cloned

      - name: Copy out miniupnpc
        run: |
          cp -RLv cloned/miniupnpc source

      - name: Install tools
        if: matrix.os.matrix != 'windows'
        run: |
          pip install cibuildwheel==2.23.0

      - name: Build and test
        if: matrix.os.matrix != 'windows'
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.os.cibw-archs-macos[matrix.arch.matrix] }}
          CIBW_BUILD: ${{ matrix.python.cibw-build }}
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=${{ matrix.os.macosx-deployment-target[matrix.arch.matrix] }}
          CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.python.manylinux }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.python.manylinux }}
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_SKIP: '*-manylinux_i686 *-win32 *-musllinux_*'
        run: |
          cibuildwheel source --output-dir dist

      - name: Build (Windows)
        if: matrix.os.matrix == 'windows'
        run: |
          cd source
          python -m pip install setuptools wheel delvewheel

          mingw32-make -f Makefile.mingw CC=gcc
          mingw32-make -f Makefile.mingw pythonmodule PYTHON=python

          python -m delvewheel repair --add-path . --include miniupnpc.dll dist/*.whl

          mkdir ../dist
          cp dist/*.whl ../dist

      - uses: Chia-Network/actions/create-venv@main
        id: create-test-venv

      - uses: Chia-Network/actions/activate-venv@main
        with:
          directories: ${{ steps.create-test-venv.outputs.activate-venv-directories }}

      - name: Install
        run: |
          pip install --no-index --only-binary :all: --find-links dist miniupnpc

      - name: Import
        run: |
          python -c 'import miniupnpc; print(miniupnpc)'

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wheel-${{ env.FILE_NAME }}
          path: ./dist
          if-no-files-found: error

  upload:
    name: 🚀 Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/upload
        with:
          package_name: ${{ env.name }}
          artifact_name: wheel
          dry_run: ${{ github.event_name != 'workflow_dispatch' }}
          vault_url: ${{ secrets.VAULT_URL }}
          aws_account: ${{ secrets.CHIA_AWS_ACCOUNT_ID }}
