name: "📦🚀 pycryptodome"

on:
  push:
    branches:
      - long_lived/**
      - main
      - release/**
    tags:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      version:
        description: "The version to build"
        required: true

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || '' }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      distribution-name: pycryptodome
      import-name: Crypto
      version: ${{ inputs.version || '3.15.0' }}
      only-major-dot-minor: "3.12"
