name: "🚀 upload"

on:
  workflow_call:
    inputs:
      distribution-name:
        required: true
        type: string
      version:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || format('{0}-{1}-{2}', github.ref, github.event_name, github.ref == 'refs/heads/main' && github.sha || '') }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    name: 🚀 Upload
    if: '${{ secrets.CHIA_AWS_ACCOUNT_ID }}' != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/upload
        with:
          package_name: ${{ inputs.distribution-name }}
          artifact_name: wheel
          dry_run: ${{ github.event_name != 'workflow_dispatch' }}
          vault_url: ${{ secrets.VAULT_URL }}
          aws_account: ${{ secrets.CHIA_AWS_ACCOUNT_ID }}
