name: "📦🚀 setproctitle"

on:
  push:
    branches:
    - long_lived/**
    - main
    - release/**
    tags:
    - '**'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:
    inputs:
      version:
        description: "The version to build"
        required: true

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || '' }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
    cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

env:
  VERSION: ${{ inputs.version || '1.3.2' }}

jobs:
  build:
    uses: ./.github/workflows/reflow-build-cibuildwheel.yml
    with:
      distribution-name: setproctitle
      import-name: setproctitle
      version: ${{ env.VERSION }}
      only-major-dot-minor: '3.8'

  upload:
    uses: ./.github/workflows/reflow-upload-to-chia-pypi.yml
    needs: build
    secrets: inherit
    with:
      distribution-name: setproctitle
      version: ${{ env.VERSION }}
