name: test

# This reusable workflow structure was chosen for the sole purpose of working around
# the 256 job per matrix limit.  The initial total test job count was 290.  This
# approach shifts the 256 limit to be per OS rather than overall.  A simpler single
# regular workflow with matrixing against the OS would be preferred.

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      vault_url:
        required: true
        type: string
      vault_token:
        required: true
        type: string
      enable:
        required: true
        type: bool

jobs:
  upload:
    runs-on: [k8s-internal]
    container:
      image: alpine:latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheel
          path: ./dist

      - name: Install deps
        run: apk add aws-cli

      - name: Vault Login
        uses: Chia-Network/actions/vault/login@main
        with:
          vault_url: ${{ inputs.vault_url }}
          role_name: github

      - name: Get ephemeral aws credentials
        uses: Chia-Network/actions/vault/aws-sts@main
        with:
          vault_url: ${{ inputs.vault_url }}
          vault_token: ${{ inputs.vault_token }}
          role_name: bootstrap

      - name: Upload Wheels
        if: inputs.enable
        working-directory: dist
        run: |
          echo just showing that we're running here, would be uploading to s3
          # TODO: enable once we think it is properly gated
          # ls dist/${{ inputs.package_name }}-*.whl | xargs -I % sh -c 'aws s3 cp % s3://download.chia.net/simple/${{ inputs.package_name }}/'
